version: 2.1
orbs:
  android: circleci/android@2.5.0
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: cimg/android:2024.01
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ .Environment.CACHE_VERSION }}-{{ checksum "build.gradle.kts" }}-{{ checksum  "composeApp/build.gradle.kts" }}
      - run:
          name: Create local.properties
          command: printf 'gemini_api_key=%s' \
            $gemini_api_key > local.properties
      - run:
          name: Decode Android key store
          command: echo $KEYSTORE_BASE64 | base64 -d | tee mabia_keystore
      - run:
          name: Decode keystore.properties 'base64 -i keystore.properties'
          command: echo $KEYSTORE_PROPERTIES | base64 -d | tee keystore.properties
      - run:
          name: Create Google Play key
          command: echo $GOOGLE_PLAY_KEY > fastlane/anwar-p-7d3150c1293d.json
#      - run:
#          name: Create Google Services JSON
#          command: echo $GOOGLE_SERVICES_JSON > composeApp/google-services.json
#      - run:
#          name: Create Fastlane Environment Variable
#          command: printf 'FIREBASE_ETONG_APP_ID_RELEASE=%s\nFIREBASE_ETONG_CLI_TOKEN=%s' \
#            $FIREBASE_ETONG_APP_ID_RELEASE $FIREBASE_ETONG_CLI_TOKEN > fastlane/.env

#      - run:
#          name: Test Composable Component `./gradlew desktopTest`
#          command: ./gradlew desktopTest

      - run:
          name: Install Fastlane
          command: sudo gem install fastlane
      - run:
          name: Uploading an AAB to Playstore (Internal)
          command: fastlane internal_playstore

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
